sonar.organization=sunilkumarba2955
sonar.projectKey=SunilKumarba2955_Sunilkumarba2955
sonar.sources=.
sonar.exclusions=.git/**,.scannerwork/**,.tools/**,.sonarlint/**,.vscode/**,.agents/**
sonar.sourceEncoding=UTF-8
